import 'package:flutter/material.dart';

import 'typography.dart';

enum AppBrightness { dark, light }

/// Builds the app's Material 3 [ThemeData] using Flutter's native Material 3
/// Expressive color system — [ColorScheme.fromSeed] with
/// [DynamicSchemeVariant.expressive] — seeded from a single fixed violet, so
/// every surface, container and text color is generated by Google's own
/// color algorithm rather than hand-picked.
class AppThemeData {
  AppThemeData._();

  static const _seedColor = Color(0xFF6C5CE0);

  static ThemeData build(Brightness brightness) {
    final scheme = ColorScheme.fromSeed(
      seedColor: _seedColor,
      brightness: brightness,
      // `expressive` deliberately shifts hue away from the seed for variety
      // (it turned our violet green) — `fidelity` keeps the generated
      // palette on the seed's actual hue while still being a native,
      // algorithmically-derived M3 tonal scheme.
      dynamicSchemeVariant: DynamicSchemeVariant.fidelity,
    );
    final base = ThemeData(
      useMaterial3: true,
      colorScheme: scheme,
      scaffoldBackgroundColor: scheme.surface,
      fontFamily: AppType.fontFamily,
    );
    return base.copyWith(
      appBarTheme: AppBarTheme(
        backgroundColor: scheme.surface,
        foregroundColor: scheme.onSurface,
        elevation: 0,
        scrolledUnderElevation: 0,
        centerTitle: false,
      ),
      cardTheme: CardThemeData(
        color: scheme.surfaceContainerLow,
        elevation: 0,
        margin: EdgeInsets.zero,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(24),
          side: BorderSide(color: scheme.outlineVariant.withValues(alpha: 0.5)),
        ),
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: scheme.surfaceContainer,
        indicatorColor: scheme.primaryContainer,
        elevation: 0,
        labelTextStyle: WidgetStateProperty.all(
          const TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
        ),
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          minimumSize: const Size.fromHeight(52),
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
          textStyle: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: scheme.surfaceContainerHighest.withValues(alpha: 0.5),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: scheme.outlineVariant),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: scheme.primary, width: 2),
        ),
      ),
      textTheme: base.textTheme.copyWith(
        displayLarge: base.textTheme.displayLarge
            ?.copyWith(fontWeight: FontWeight.w800, letterSpacing: -0.5),
        headlineMedium: base.textTheme.headlineMedium
            ?.copyWith(fontWeight: FontWeight.w800, letterSpacing: -0.4),
        headlineSmall: base.textTheme.headlineSmall
            ?.copyWith(fontWeight: FontWeight.w700, letterSpacing: -0.3),
        titleLarge: base.textTheme.titleLarge
            ?.copyWith(fontWeight: FontWeight.w700, letterSpacing: -0.2),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          minimumSize: const Size.fromHeight(52),
          side: BorderSide(color: scheme.outline),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          textStyle: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          textStyle: const TextStyle(fontWeight: FontWeight.w600),
        ),
      ),
      chipTheme: ChipThemeData(
        backgroundColor: scheme.surfaceContainerHigh,
        selectedColor: scheme.primaryContainer,
        labelStyle: TextStyle(color: scheme.onSurface, fontWeight: FontWeight.w600),
        secondaryLabelStyle:
            TextStyle(color: scheme.onPrimaryContainer, fontWeight: FontWeight.w600),
        side: BorderSide.none,
        shape: const StadiumBorder(),
        showCheckmark: false,
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
      ),
      segmentedButtonTheme: SegmentedButtonThemeData(
        style: SegmentedButton.styleFrom(
          selectedBackgroundColor: scheme.primaryContainer,
          selectedForegroundColor: scheme.onPrimaryContainer,
          shape: const StadiumBorder(),
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: scheme.primaryContainer,
        foregroundColor: scheme.onPrimaryContainer,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      ),
      bottomSheetTheme: BottomSheetThemeData(
        backgroundColor: scheme.surface,
        modalBackgroundColor: scheme.surface,
        elevation: 0,
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        ),
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: scheme.surfaceContainerHigh,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(28)),
      ),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: scheme.inverseSurface,
        contentTextStyle: TextStyle(color: scheme.onInverseSurface),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      ),
      dividerTheme: DividerThemeData(color: scheme.outlineVariant, thickness: 1),
      progressIndicatorTheme: ProgressIndicatorThemeData(color: scheme.primary),
      switchTheme: SwitchThemeData(
        thumbColor: WidgetStateProperty.resolveWith((states) =>
            states.contains(WidgetState.selected) ? scheme.primary : null),
        trackColor: WidgetStateProperty.resolveWith((states) =>
            states.contains(WidgetState.selected) ? scheme.primaryContainer : null),
      ),
    );
  }
}

/// Semantic color bridge over the active [ColorScheme] (`c.accent`,
/// `c.income`, …) used throughout the app's screens.
class AppColors {
  final ColorScheme scheme;
  const AppColors(this.scheme);

  static AppColors of(BuildContext context) =>
      AppColors(Theme.of(context).colorScheme);

  bool get isDark => scheme.brightness == Brightness.dark;

  Color get background => scheme.surface;
  Color get backgroundAlt => scheme.surfaceContainerLowest;
  Color get surface => scheme.surfaceContainerLow;
  Color get surfaceElevated => scheme.surfaceContainerHigh;
  Color get surfaceGlass => scheme.surfaceContainer.withValues(alpha: 0.7);
  Color get hairline => scheme.outlineVariant.withValues(alpha: 0.6);
  Color get textPrimary => scheme.onSurface;
  Color get textSecondary => scheme.onSurfaceVariant;
  Color get textTertiary => scheme.onSurfaceVariant.withValues(alpha: 0.65);
  Color get accent => scheme.primary;
  Color get accentDeep => scheme.primary;
  Color get accentSoft => scheme.primary.withValues(alpha: 0.12);
  Color get onAccent => scheme.onPrimary;
  // Fixed finance semantics: green/red convey direction consistently across
  // every accent color, the way income/expense colors work in most finance
  // apps regardless of brand theme.
  Color get income => isDark ? const Color(0xFF4ADE80) : const Color(0xFF1B8E5A);
  Color get expense => isDark ? const Color(0xFFFF8A98) : const Color(0xFFD64550);
  Color get warning => isDark ? const Color(0xFFFBBF24) : const Color(0xFFB45309);
  Color get info => isDark ? const Color(0xFF7DB8FF) : const Color(0xFF2563EB);
  // Soft warning "container" pairing (M3 container/on-container convention)
  // for callouts that need a tinted background, not just warning-colored text.
  Color get warningContainer => isDark ? const Color(0xFF4A3313) : const Color(0xFFFEF0D6);
  Color get onWarningContainer => isDark ? const Color(0xFFFBBF24) : const Color(0xFF7A4A05);
  Color get shadow => Colors.black;
}

/// Back-compat shim: older code referenced `AppTheme.of(context)`.
class AppTheme {
  static AppColors of(BuildContext context) => AppColors.of(context);
}
